 stages:
  - test
  - build
  - deploy
 
 Application Unit Testing:
    stage: test
    image: 192.168.2.113:5000/laravel
 
    script:
      - cp env.$CI_COMMIT_BRANCH .env
      - php artisan key:generate
      - echo "$(pwd)"
      - vendor/bin/phpunit
      - echo $CI_COMMIT_BRANCH
      
    only:
       refs:
         - Development
       variables:
         - $CI_COMMIT_MESSAGE =~ /bungkus/
    tags:
      - kubernetes
 
 Application Building:
 
    stage: build
    image: 192.168.2.113:5000/alpine
    variables:
      S3_BUCKET_NAME: "artifacts"
    only:
       refs:
         - Development
         - Staging
         - master
       variables:
         - $CI_COMMIT_MESSAGE =~ /bungkus & bangun/
         - $CI_COMMIT_MESSAGE =~ /bungkus & produksi/
         - $CI_COMMIT_MESSAGE =~ /s3/
  
    script:
      - tanggal=$(date +%F-%H%M%S)
      - echo "$(pwd)"
      - cp env.$CI_COMMIT_BRANCH .env
      - echo $(ls)
      - zip -r $tanggal.zip .
      - echo $(ls)
      - file=$tanggal.zip
      - target=s3://artifacts/$CI_COMMIT_BRANCH/$file
      - echo "aws s3 cp $file $target --endpoint-url=http://192.168.2.4:7200"
      - aws s3 cp $tanggal.zip $target --endpoint-url=http://192.168.2.4:7200
   
    tags:
      - kubernetes
 
 Application Deployment:
 
    stage: deploy
    script:
     - echo "$(pwd)"
     - echo "$(ls)"
     - echo $USER
     - docker build -t laravel_image .
     - docker tag laravel_image 192.168.2.113:5000/laravel_image
     - docker push 192.168.2.113:5000/laravel_image
     - >
      var=“$(curl -u admin:Nut4nixP@ssw0rd -k -X POST -H 'Content-Type: application/json' https://192.168.1.45:9440/api/nutanix/v3/apps/list -d "{\"kind\":\"app\",\"filter\":\"name==APR_Hotel\”}”)”
     - if echo "$var" | grep -q '"total_matches":1'; then hasil="cocok"; else hasil="gagal";fi
     - >-
      curl -u admin:Nut4nixP@ssw0rd -k -X POST https://192.168.1.45:9440/api/nutanix/v3/blueprints/20343a63-1b3b-4929-ab46-d0bdeb565773/simple_launch -H 'Content-Type: application/json' -d '{"spec": { "app_name": "APR_Hotel", "app_description": "Demo blueprint launch via the v3 REST API", "app_profile_reference": { "kind": "app_profile", "name": "Default", "uuid": "8b6e032b-5315-4fd4-a350-03005e4710c3"}}}'
    only:
       refs:
         - Development
         - Staging
         - master
       variables:
         - $CI_COMMIT_MESSAGE =~ /bungkus & produksi/
         - $CI_COMMIT_MESSAGE =~ /nyalip/
         - $var == "gagal"
    tags:
      - vm_runner
      
 